import tkinter as tk
root = tk.Tk()
root.geometry('500x700')
root.title("Physics X Python")
label = tk.Label(root, text="Hellow guys !!!", font=('Arial',18))
label.pack()
textbox = tk.Text(root,height =1, font=('Arial',18))
textbox.pack(pady=10,padx=10)

button = tk.Frame(root)
button.columnconfigure(0, weight=1)
button.columnconfigure(1, weight=1)
button.columnconfigure(2, weight=1)

btn1 = tk.Button(button, text='1', font=('Arial', 18))
btn1.grid(row=0,column=0, sticky=tk.W+tk.E)
btn2 = tk.Button(button, text='2', font=('Arial', 18))
btn2.grid(row=0,column=1, sticky=tk.W+tk.E)
btn3 = tk.Button(button, text='3', font=('Arial', 18))
btn3.grid(row=0,column=2, sticky=tk.W+tk.E)
btn4 = tk.Button(button, text='4', font=('Arial', 18))
btn4.grid(row=1,column=0, sticky=tk.W+tk.E)
btn5 = tk.Button(button, text='5', font=('Arial', 18))
btn5.grid(row=1,column=1, sticky=tk.W+tk.E)
btn6 = tk.Button(button, text='6', font=('Arial', 18))
btn6.grid(row=1,column=2, sticky=tk.W+tk.E)
btn7 = tk.Button(button, text='7', font=('Arial', 18))
btn7.grid(row=2,column=0, sticky=tk.W+tk.E)
btn8 = tk.Button(button, text='8', font=('Arial', 18))
btn8.grid(row=2,column=1, sticky=tk.W+tk.E)
btn9 = tk.Button(button, text='9', font=('Arial', 18))
btn9.grid(row=2,column=2, sticky=tk.W+tk.E)
btn0 = tk.Button(button, text='0', font=('Arial', 18))
btn0.grid(row=3,column=1, sticky=tk.W+tk.E)
button.pack(fill='x')

root.mainloop()